version: "3.3"

services:
  php:
    build: ./php
    volumes:
      - ./public:/var/www/html/public

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
